export type Action = {
  id: string;
  category: string;
  label: string;
  benefitHours: [number, number];
  costTier: "none" | "low" | "medium" | "high";
  authority: "handler" | "supervisor" | "ops-control";
  executionMinutes: number;
  requiresStationCapability: string[];
  applicableStates: string[];
  applicableShc: string[];
};

export const ACTION_LIBRARY: Action[] = [
  {
    id: "storage-cool-room-001",
    category: "storage",
    label: "Move to certified cool room",
    benefitHours: [6, 12],
    costTier: "none",
    authority: "handler",
    executionMinutes: 8,
    requiresStationCapability: ["coolRoomSlotsTotal"],
    applicableStates: ["in-warehouse", "in-buildup", "in-storage"],
    applicableShc: ["AVI", "COL", "CRT", "FRO", "HEG", "PER"],
  },
  {
    id: "storage-ac-vent-001",
    category: "storage",
    label: "Stage near AC vent",
    benefitHours: [2, 4],
    costTier: "none",
    authority: "handler",
    executionMinutes: 6,
    requiresStationCapability: [],
    applicableStates: ["in-warehouse", "in-buildup", "in-storage"],
    applicableShc: ["AVI", "COL", "CRT", "HEG", "PER"],
  },
  {
    id: "equipment-thermal-blanket-001",
    category: "equipment",
    label: "Apply thermal blanket",
    benefitHours: [2, 5],
    costTier: "low",
    authority: "handler",
    executionMinutes: 7,
    requiresStationCapability: ["thermalBlanketStock"],
    applicableStates: ["in-warehouse", "in-buildup", "in-tarmac", "in-storage"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "ops-priority-buildup-slot-001",
    category: "ops",
    label: "Priority build-up slot",
    benefitHours: [1, 3],
    costTier: "medium",
    authority: "supervisor",
    executionMinutes: 15,
    requiresStationCapability: ["buildupBaysTotal"],
    applicableStates: ["in-warehouse", "in-buildup"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "cooling-reprecondition-pcm-001",
    category: "cooling",
    label: "Re-pre-condition PCM packs",
    benefitHours: [8, 12],
    costTier: "high",
    authority: "ops-control",
    executionMinutes: 30,
    requiresStationCapability: ["coolRoomSlotsTotal"],
    applicableStates: ["in-warehouse", "in-storage"],
    applicableShc: ["COL", "FRO", "PER"],
  },
  {
    id: "cool-dolly-001",
    category: "logistics",
    label: "Use refrigerated cool dolly",
    benefitHours: [3, 6],
    costTier: "medium",
    authority: "handler",
    executionMinutes: 6,
    requiresStationCapability: ["coolDolliesTotal"],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "shade-insulated-tarp-001",
    category: "shading",
    label: "Insulated thermal tarp",
    benefitHours: [1, 2],
    costTier: "low",
    authority: "handler",
    executionMinutes: 12,
    requiresStationCapability: ["thermalBlanketStock"],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "COL", "HEG", "PER"],
  },
  {
    id: "ops-cooler-window-001",
    category: "ops",
    label: "Tow during cooler window",
    benefitHours: [2, 4],
    costTier: "medium",
    authority: "supervisor",
    executionMinutes: 20,
    requiresStationCapability: [],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "shade-jet-bridge-001",
    category: "shading",
    label: "Park in jet-bridge shadow",
    benefitHours: [2, 5],
    costTier: "none",
    authority: "handler",
    executionMinutes: 4,
    requiresStationCapability: ["shadingZones"],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "COL", "CRT", "FRO", "HEG", "PER"],
  },
  {
    id: "shade-tail-shadow-001",
    category: "shading",
    label: "Park in aircraft tail shadow",
    benefitHours: [1, 3],
    costTier: "none",
    authority: "handler",
    executionMinutes: 15,
    requiresStationCapability: ["shadingZones"],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "COL", "CRT", "FRO", "HEG", "PER"],
  },
  {
    id: "shade-reflective-cover-001",
    category: "shading",
    label: "Reflective tarp / silver cover",
    benefitHours: [2, 4],
    costTier: "low",
    authority: "handler",
    executionMinutes: 15,
    requiresStationCapability: ["thermalBlanketStock"],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "cooling-wet-rag-001",
    category: "cooling",
    label: "Wet-rag evaporative cooling",
    benefitHours: [1, 2],
    costTier: "none",
    authority: "handler",
    executionMinutes: 8,
    requiresStationCapability: ["wetRagAuthorised"],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "HEG"],
  },
  {
    id: "ops-priority-loading-slot-001",
    category: "ops",
    label: "Request priority loading slot",
    benefitHours: [1, 3],
    costTier: "medium",
    authority: "supervisor",
    executionMinutes: 12,
    requiresStationCapability: [],
    applicableStates: ["in-tarmac"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "crew-gpu-precool-001",
    category: "crew",
    label: "Aircraft GPU + AC pre-cool",
    benefitHours: [3, 6],
    costTier: "high",
    authority: "ops-control",
    executionMinutes: 20,
    requiresStationCapability: [],
    applicableStates: ["in-transit", "in-flight"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "crew-keep-door-closed-001",
    category: "crew",
    label: "Keep cargo door closed",
    benefitHours: [1, 2],
    costTier: "none",
    authority: "supervisor",
    executionMinutes: 10,
    requiresStationCapability: [],
    applicableStates: ["in-transit", "in-flight"],
    applicableShc: [],
  },
  {
    id: "ops-shaded-gate-001",
    category: "ops",
    label: "Reposition aircraft to shaded gate",
    benefitHours: [2, 4],
    costTier: "high",
    authority: "ops-control",
    executionMinutes: 25,
    requiresStationCapability: ["shadingZones"],
    applicableStates: ["in-tarmac", "in-transit"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "logistics-fresh-passive-uld-001",
    category: "logistics",
    label: "Swap to fresh passive ULD",
    benefitHours: [8, 12],
    costTier: "high",
    authority: "ops-control",
    executionMinutes: 35,
    requiresStationCapability: [],
    applicableStates: ["in-warehouse", "in-buildup", "in-storage", "in-tarmac"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "logistics-active-uld-001",
    category: "logistics",
    label: "Swap to active ULD",
    benefitHours: [12, 24],
    costTier: "high",
    authority: "ops-control",
    executionMinutes: 45,
    requiresStationCapability: [],
    applicableStates: ["in-warehouse", "in-buildup", "in-storage", "in-tarmac"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "logistics-reroute-cooler-hub-001",
    category: "logistics",
    label: "Reroute via cooler hub",
    benefitHours: [4, 10],
    costTier: "high",
    authority: "ops-control",
    executionMinutes: 40,
    requiresStationCapability: [],
    applicableStates: ["in-transit", "in-flight", "in-storage"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "ops-hold-rebook-001",
    category: "ops",
    label: "Hold + re-book later flight",
    benefitHours: [6, 10],
    costTier: "high",
    authority: "ops-control",
    executionMinutes: 30,
    requiresStationCapability: [],
    applicableStates: ["in-warehouse", "in-storage", "in-tarmac"],
    applicableShc: ["AVI", "COL", "FRO", "HEG", "PER"],
  },
  {
    id: "DOC-001",
    category: "documentation",
    label: "Document (no-mitigation fallback)",
    benefitHours: [0, 0],
    costTier: "none",
    authority: "handler",
    executionMinutes: 5,
    requiresStationCapability: [],
    applicableStates: [
      "in-tarmac",
      "in-buildup",
      "in-warehouse",
      "in-transit",
      "in-storage",
    ],
    applicableShc: [],
  },
  {
    id: "doc-notify-shipper-001",
    category: "documentation",
    label: "Notify shipper for batch hold",
    benefitHours: [0, 0.5],
    costTier: "none",
    authority: "handler",
    executionMinutes: 5,
    requiresStationCapability: [],
    applicableStates: [
      "in-tarmac",
      "in-buildup",
      "in-warehouse",
      "in-transit",
      "in-storage",
    ],
    applicableShc: [],
  },
  {
    id: "doc-insurance-001",
    category: "documentation",
    label: "Insurance pre-notification",
    benefitHours: [0, 0.5],
    costTier: "none",
    authority: "handler",
    executionMinutes: 6,
    requiresStationCapability: [],
    applicableStates: ["in-tarmac", "in-transit", "in-storage"],
    applicableShc: [],
  },
  {
    id: "monitoring-sensor-polling-001",
    category: "monitoring",
    label: "Increase sensor polling cadence",
    benefitHours: [0.1, 0.3],
    costTier: "none",
    authority: "handler",
    executionMinutes: 5,
    requiresStationCapability: [],
    applicableStates: [
      "in-tarmac",
      "in-buildup",
      "in-warehouse",
      "in-transit",
      "in-storage",
    ],
    applicableShc: [],
  },
  {
    id: "handling-temp-check-001",
    category: "handling",
    label: "Manual temperature spot check",
    benefitHours: [0, 0.1],
    costTier: "none",
    authority: "handler",
    executionMinutes: 5,
    requiresStationCapability: [],
    applicableStates: ["in-tarmac", "in-buildup", "in-warehouse", "in-storage"],
    applicableShc: [],
  },
];
